# Generated by Django 5.2.7 on 2025-12-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('acham_history', 'Acham History'), ('work_with_us', 'Work With Us')], help_text='Type of static page', max_length=50, unique=True, verbose_name='Page Type')),
                ('title', models.CharField(help_text='Page title', max_length=255, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Page title', max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Page title', max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(help_text='Page title', max_length=255, null=True, verbose_name='Title')),
                ('content', models.TextField(help_text='Page content (HTML allowed)', verbose_name='Content')),
                ('content_ru', models.TextField(help_text='Page content (HTML allowed)', null=True, verbose_name='Content')),
                ('content_en', models.TextField(help_text='Page content (HTML allowed)', null=True, verbose_name='Content')),
                ('content_uz', models.TextField(help_text='Page content (HTML allowed)', null=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['page_type'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(help_text='Answer for this FAQ', null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(help_text='Answer for this FAQ', null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(help_text='Answer for this FAQ', null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(help_text='Question for this FAQ', max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(help_text='Question for this FAQ', max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(help_text='Question for this FAQ', max_length=255, null=True, verbose_name='Question'),
        ),
    ]
