# Generated by Django 5.2.7 on 2025-12-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_staticpage_faq_answer_en_faq_answer_ru_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Contact's first name", max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Contact's last name", max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="Contact's email address", max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="Contact's phone number", max_length=64, verbose_name='Phone Number')),
                ('subject', models.CharField(blank=True, help_text='Message subject/title', max_length=255, verbose_name='Subject')),
                ('message', models.TextField(help_text="Contact's message", verbose_name='Message')),
                ('subscribe_to_newsletter', models.BooleanField(default=False, help_text='Whether the contact wants to subscribe to newsletter', verbose_name='Subscribe to Newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
