# Generated by Django 5.2.7 on 2025-12-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, help_text='Page image (optional)', null=True, upload_to='static_pages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('acham_history', 'Acham History'), ('work_with_us', 'Work With Us'), ('declaration_of_conformity', 'Declaration of Conformity')], help_text='Type of static page', max_length=50, unique=True, verbose_name='Page Type'),
        ),
    ]
