# Generated by Django 5.2.7 on 2025-12-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_delete_banner_staticpage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Order number for the return request', max_length=255, verbose_name='Order Number')),
                ('email_or_phone', models.CharField(help_text='Contact email or phone number', max_length=255, verbose_name='Email or Phone Number')),
                ('message', models.TextField(help_text='Return request message/details', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subscribe_to_newsletter',
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('acham_history', 'Acham History'), ('work_with_us', 'Work With Us'), ('declaration_of_conformity', 'Declaration of Conformity'), ('returns', 'Returns')], help_text='Type of static page', max_length=50, unique=True, verbose_name='Page Type'),
        ),
    ]
