# Generated by Django 5.2.7 on 2025-12-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_returnrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for newsletter subscription', max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
