# Generated by Django 5.2.7 on 2025-12-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], default='ru', help_text='Preferred language for emails', max_length=2, verbose_name='Language'),
        ),
    ]
