# Generated by Django 5.2.7 on 2026-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_aboutpagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesection',
            name='content_en',
            field=models.TextField(blank=True, help_text='Section content text', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='content_ru',
            field=models.TextField(blank=True, help_text='Section content text', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='content_uz',
            field=models.TextField(blank=True, help_text='Section content text', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='founder_name_en',
            field=models.CharField(blank=True, help_text='Name of the founder (for hero section)', max_length=255, null=True, verbose_name='Founder Name'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='founder_name_ru',
            field=models.CharField(blank=True, help_text='Name of the founder (for hero section)', max_length=255, null=True, verbose_name='Founder Name'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='founder_name_uz',
            field=models.CharField(blank=True, help_text='Name of the founder (for hero section)', max_length=255, null=True, verbose_name='Founder Name'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='founder_title_en',
            field=models.CharField(blank=True, help_text="Title/role of the founder (e.g., 'Founder of ACHAM')", max_length=255, null=True, verbose_name='Founder Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='founder_title_ru',
            field=models.CharField(blank=True, help_text="Title/role of the founder (e.g., 'Founder of ACHAM')", max_length=255, null=True, verbose_name='Founder Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='founder_title_uz',
            field=models.CharField(blank=True, help_text="Title/role of the founder (e.g., 'Founder of ACHAM')", max_length=255, null=True, verbose_name='Founder Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_description_en',
            field=models.TextField(blank=True, help_text='Description for process section', null=True, verbose_name='Process Description'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_description_ru',
            field=models.TextField(blank=True, help_text='Description for process section', null=True, verbose_name='Process Description'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_description_uz',
            field=models.TextField(blank=True, help_text='Description for process section', null=True, verbose_name='Process Description'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Section title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Section title', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Section title', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
