# Generated by Django 5.2.7 on 2026-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0010_aboutpagesection_content_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagesection',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='order',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_content',
            field=models.TextField(blank=True, help_text='Content for fabrics section', verbose_name='Fabrics Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_content_en',
            field=models.TextField(blank=True, help_text='Content for fabrics section', null=True, verbose_name='Fabrics Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_content_ru',
            field=models.TextField(blank=True, help_text='Content for fabrics section', null=True, verbose_name='Fabrics Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_content_uz',
            field=models.TextField(blank=True, help_text='Content for fabrics section', null=True, verbose_name='Fabrics Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_image',
            field=models.ImageField(blank=True, help_text='Main image for fabrics section', null=True, upload_to='about_page/', verbose_name='Fabrics Image'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_image_2',
            field=models.ImageField(blank=True, help_text='Additional image for fabrics section', null=True, upload_to='about_page/', verbose_name='Fabrics Image 2'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_image_3',
            field=models.ImageField(blank=True, help_text='Additional image for fabrics section', null=True, upload_to='about_page/', verbose_name='Fabrics Image 3'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_title',
            field=models.CharField(blank=True, help_text='Title for fabrics section', max_length=255, verbose_name='Fabrics Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_title_en',
            field=models.CharField(blank=True, help_text='Title for fabrics section', max_length=255, null=True, verbose_name='Fabrics Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_title_ru',
            field=models.CharField(blank=True, help_text='Title for fabrics section', max_length=255, null=True, verbose_name='Fabrics Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='fabrics_title_uz',
            field=models.CharField(blank=True, help_text='Title for fabrics section', max_length=255, null=True, verbose_name='Fabrics Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_content',
            field=models.TextField(blank=True, help_text='Content for history section', verbose_name='History Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_content_en',
            field=models.TextField(blank=True, help_text='Content for history section', null=True, verbose_name='History Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_content_ru',
            field=models.TextField(blank=True, help_text='Content for history section', null=True, verbose_name='History Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_content_uz',
            field=models.TextField(blank=True, help_text='Content for history section', null=True, verbose_name='History Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_image',
            field=models.ImageField(blank=True, help_text='Image for history section', null=True, upload_to='about_page/', verbose_name='History Image'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_title',
            field=models.CharField(blank=True, help_text='Title for history section', max_length=255, verbose_name='History Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_title_en',
            field=models.CharField(blank=True, help_text='Title for history section', max_length=255, null=True, verbose_name='History Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_title_ru',
            field=models.CharField(blank=True, help_text='Title for history section', max_length=255, null=True, verbose_name='History Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='history_title_uz',
            field=models.CharField(blank=True, help_text='Title for history section', max_length=255, null=True, verbose_name='History Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_content',
            field=models.TextField(blank=True, help_text='Content for philosophy section', verbose_name='Philosophy Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_content_en',
            field=models.TextField(blank=True, help_text='Content for philosophy section', null=True, verbose_name='Philosophy Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_content_ru',
            field=models.TextField(blank=True, help_text='Content for philosophy section', null=True, verbose_name='Philosophy Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_content_uz',
            field=models.TextField(blank=True, help_text='Content for philosophy section', null=True, verbose_name='Philosophy Content'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_image',
            field=models.ImageField(blank=True, help_text='Image for philosophy section', null=True, upload_to='about_page/', verbose_name='Philosophy Image'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_title',
            field=models.CharField(blank=True, help_text='Title for philosophy section', max_length=255, verbose_name='Philosophy Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_title_en',
            field=models.CharField(blank=True, help_text='Title for philosophy section', max_length=255, null=True, verbose_name='Philosophy Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_title_ru',
            field=models.CharField(blank=True, help_text='Title for philosophy section', max_length=255, null=True, verbose_name='Philosophy Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='philosophy_title_uz',
            field=models.CharField(blank=True, help_text='Title for philosophy section', max_length=255, null=True, verbose_name='Philosophy Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_title',
            field=models.CharField(blank=True, help_text='Title for process section', max_length=255, verbose_name='Process Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_title_en',
            field=models.CharField(blank=True, help_text='Title for process section', max_length=255, null=True, verbose_name='Process Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_title_ru',
            field=models.CharField(blank=True, help_text='Title for process section', max_length=255, null=True, verbose_name='Process Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='process_title_uz',
            field=models.CharField(blank=True, help_text='Title for process section', max_length=255, null=True, verbose_name='Process Title'),
        ),
        migrations.AlterField(
            model_name='aboutpagesection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the page is displayed', verbose_name='Is Active'),
        ),
    ]
