# Generated by Django 5.2.7 on 2025-11-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20251110_0001'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='users_phone_phone_65101d_idx',
            old_name='users_phone_phone_pu_f2d8c3_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='users_phone_expires_6954f2_idx',
            old_name='users_phone_expires_1d7468_idx',
        ),
    ]
