# Generated by Django 5.2.7 on 2025-12-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_users_phone_phone_pu_f2d8c3_idx_users_phone_phone_65101d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone OTP'), ('social', 'Social Network')], default='email', help_text='Method used for user registration', max_length=20, verbose_name='Registration method'),
        ),
    ]
