# Generated by Django 5.2.7 on 2026-01-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_token_a2ec75_idx',
            old_name='users_pass_token_9a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_expires_853bc2_idx',
            old_name='users_pass_expires_7c3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_user_id_7456f8_idx',
            old_name='users_pass_user_id_5e6f7g_idx',
        ),
    ]
