# Generated by Django 5.2.7 on 2026-02-06 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_users_pass_token_9a8b2c_idx_users_passw_token_a2ec75_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='OTP Code')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session Key')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Attempts')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin OTP',
                'verbose_name_plural': 'Admin OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'is_active'], name='users_admin_session_235e4d_idx'), models.Index(fields=['expires_at'], name='users_admin_expires_fe9cd3_idx'), models.Index(fields=['user', 'is_active'], name='users_admin_user_id_2e5c76_idx')],
            },
        ),
    ]
