# Generated by Django 5.2.7 on 2025-10-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product', max_length=200, verbose_name='Product Name')),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('one_size', 'One Size')], help_text='Product size', max_length=20, verbose_name='Size')),
                ('material', models.CharField(help_text='Primary material of the product', max_length=100, verbose_name='Material')),
                ('type', models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('jewelry', 'Jewelry'), ('other', 'Other')], help_text='Category of the product', max_length=20, verbose_name='Product Type')),
                ('color', models.CharField(help_text='Primary color of the product', max_length=50, verbose_name='Color')),
                ('short_description', models.TextField(blank=True, help_text='Brief description of the product', max_length=500, verbose_name='Short Description')),
                ('detailed_description', models.TextField(blank=True, help_text='Comprehensive description with features and benefits', verbose_name='Detailed Description')),
                ('care_instructions', models.TextField(blank=True, help_text='How to care for and maintain the product', verbose_name='Care Instructions')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, verbose_name='Price')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the product is currently available', verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image', upload_to='products/shots/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200, verbose_name='Alt Text')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the main product image', verbose_name='Primary Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Shot',
                'verbose_name_plural': 'Product Shots',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
