# Generated by Django 5.2.7 on 2025-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collection_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the collection', null=True, upload_to='collections/', verbose_name='Image'),
        ),
    ]
