# Generated by Django 5.2.7 on 2025-10-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_collection_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
