# Generated by Django 5.2.7 on 2025-10-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
