# Generated by Django 5.2.7 on 2025-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_collection_is_featured_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name_ru',
            field=models.CharField(help_text='Name of the collection', max_length=200, null=True, verbose_name='Collection Name'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(help_text='Name of the collection', max_length=200, null=True, verbose_name='Collection Name'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_uz',
            field=models.CharField(help_text='Name of the collection', max_length=200, null=True, verbose_name='Collection Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_ru',
            field=models.TextField(blank=True, help_text='How to care for and maintain the product', null=True, verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_en',
            field=models.TextField(blank=True, help_text='How to care for and maintain the product', null=True, verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_uz',
            field=models.TextField(blank=True, help_text='How to care for and maintain the product', null=True, verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(help_text='Primary color of the product', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(help_text='Primary color of the product', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_uz',
            field=models.CharField(help_text='Primary color of the product', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_ru',
            field=models.TextField(blank=True, help_text='Comprehensive description with features and benefits', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_en',
            field=models.TextField(blank=True, help_text='Comprehensive description with features and benefits', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_uz',
            field=models.TextField(blank=True, help_text='Comprehensive description with features and benefits', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(help_text='Primary material of the product', max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(help_text='Primary material of the product', max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_uz',
            field=models.CharField(help_text='Primary material of the product', max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(help_text='The name of the product', max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(help_text='The name of the product', max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(help_text='The name of the product', max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Brief description of the product', max_length=500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Brief description of the product', max_length=500, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uz',
            field=models.TextField(blank=True, help_text='Brief description of the product', max_length=500, null=True, verbose_name='Short Description'),
        ),
    ]
