# Generated by Django 5.2.7 on 2025-12-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_collection_name_en_collection_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('oversize', 'Oversize')], help_text='Product size', max_length=20, verbose_name='Size'),
        ),
    ]
