# Generated by Django 5.2.7 on 2025-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_uzs',
            field=models.DecimalField(decimal_places=2, default=1500, help_text='Product price in Uzbekistani Som (required for Uzbekistan)', max_digits=12, verbose_name='Price (UZS)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Product price (USD)', max_digits=10, verbose_name='Price'),
        ),
    ]
