# Generated by Django 5.2.7 on 2026-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_collection_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Image of the collection for mobile version', null=True, upload_to='collections/mobile/', verbose_name='Mobile Image'),
        ),
    ]
