# Generated by Django 5.2.7 on 2026-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_collection_mobile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.AddField(
            model_name='collection',
            name='slug_en',
            field=models.SlugField(blank=True, help_text='URL-friendly name for English pages', max_length=200, null=True, verbose_name='Slug (EN)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug_ru',
            field=models.SlugField(blank=True, help_text='URL-friendly name for Russian pages', max_length=200, null=True, verbose_name='Slug (RU)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug_uz',
            field=models.SlugField(blank=True, help_text='URL-friendly name for Uzbek pages', max_length=200, null=True, verbose_name='Slug (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(blank=True, help_text='URL-friendly name for English product page', max_length=200, null=True, verbose_name='Slug (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=models.SlugField(blank=True, help_text='URL-friendly name for Russian product page', max_length=200, null=True, verbose_name='Slug (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_uz',
            field=models.SlugField(blank=True, help_text='URL-friendly name for Uzbek product page', max_length=200, null=True, verbose_name='Slug (UZ)'),
        ),
    ]
