# Generated by Django 5.2.7 on 2025-10-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Administrative title for this banner', max_length=255, verbose_name='Title')),
                ('video', models.FileField(blank=True, help_text='Banner video file (e.g., MP4, WebM)', null=True, upload_to='banners/videos/', verbose_name='Video')),
                ('image', models.ImageField(blank=True, help_text='Fallback image when video cannot be played', null=True, upload_to='banners/images/', verbose_name='Image Fallback')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is active on the homepage', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
