# Generated by Django 5.2.7 on 2025-10-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the collection', max_length=200, verbose_name='Collection Name')),
                ('description', models.TextField(blank=True, help_text='Description of the collection', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this collection is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.collection', verbose_name='Collection'),
        ),
    ]
