# Generated by Django 5.2.7 on 2025-10-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_collection_is_new_arrival_cart_productshare_cartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('complete_the_look', 'Complete the Look'), ('you_may_also_like', 'You May Also Like'), ('frequently_bought_together', 'Frequently Bought Together'), ('similar_products', 'Similar Products'), ('accessories', 'Accessories'), ('outfit_complete', 'Outfit Complete')], help_text='Type of relationship between products', max_length=30, verbose_name='Relation Type')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first (0 = lowest priority)', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this relationship is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='products.product', verbose_name='Source Product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from_products', to='products.product', verbose_name='Target Product')),
            ],
            options={
                'verbose_name': 'Product Relation',
                'verbose_name_plural': 'Product Relations',
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('source_product', 'target_product', 'relation_type')},
            },
        ),
    ]
