# Generated by Django 5.2.7 on 2025-12-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTransactionStatus',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_shop_tr_1e09a5_idx',
            old_name='orders_paym_shop_tr_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_octo_tr_638f79_idx',
            old_name='orders_paym_octo_tr_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_status_735512_idx',
            old_name='orders_paym_status_ghi789_idx',
        ),
    ]