# Generated by Django 5.2.7 on 2025-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_paymenttransaction_octo_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'Payment transaction', 'verbose_name_plural': 'Payment transactions'},
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='orders_paym_shop_tr_1e09a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='orders_paym_octo_tr_638f79_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='orders_paym_status_735512_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='octo_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='octo_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='seconds_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='shop_transaction_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('PREPARED', 'Подготовлено'), ('VERIFICATION_REQUIRED', 'Требуется верификация'), ('PROCESSING', 'В обработке'), ('SUCCESS', 'Успешно'), ('FAILED', 'Неуспешно'), ('CANCELLED', 'Отменено'), ('REFUNDED', 'Возвращено')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='verification_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
