# Generated by Django 5.2.7 on 2025-12-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, RUB)', max_length=3, unique=True, verbose_name='Currency Code')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Exchange rate: 1 foreign currency = X UZS', max_digits=12, verbose_name='Rate')),
                ('date', models.DateField(help_text='Date when this rate was effective', verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['-date', 'code'],
                'indexes': [models.Index(fields=['code', '-date'], name='orders_curr_code_e63d54_idx'), models.Index(fields=['-date'], name='orders_curr_date_67c393_idx')],
            },
        ),
    ]
